cinevault/urls.py
from django.contrib import admin
from django.urls import path,include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()
urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

movies/urls.py
from django.urls import path
from . import views
app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
# Create your models here.
class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['watch_date']

movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    ratings = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    watch_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

cinevault/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies}) 

def detail(request,movie_id):
    movie = get_object_or_404(Movie,pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
 <dl>
    <dt>Year</dt>
    <dd>{{ movie.release_year }}</dd>
    <dt>Title</dt>
    <dd>{{ movie.title }}</dd>
    <dt>Genre</dt>
    <dd>{{ movie.genre }}</dd>
    <dt>Ratings</dt>
    <dd>{{ movie.ratings }}</dd>
 </dl>
{% endblock %}

movies/templates/movies/index.html
{%extends 'base.html' %}

{% block content%}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Release Year</th>
                <th>Genre</th>
                <th>Rating</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                    <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
                    <td>{{ movie.release_year }}</td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.ratings }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}